In [10]:
import random
from datetime import datetime
from datetime import timedelta

import pandas as pd
from faker import Faker

In [11]:
Faker.seed(42)
fake = Faker(['ko_KR', 'en_US'])

In [12]:
data = [{
    "id": i + 1,
    "name": fake.name(),
    "age": fake.random_int(min=20, max=65),
    "weight": fake.random_int(min=10, max=250),
    "height": fake.random_int(min=10, max=250),
    "gender": random.choice(['남성', '여성']),
    "address": fake.address(),
    "job": fake.job(),
    "email": fake.email(),
    "signup": (datetime.now() - timedelta(days=random.randint(0, 365))).date().isoformat()
} for i in range(10000)]

### Pandas Display 설정

In [ ]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", 50)
pd.set_option("display.width", 200)
pd.set_option("display.expand_frame_repr", False)

### Pandas DataFrame 만들기

In [13]:
source_dataframe = pd.DataFrame(data)
source_dataframe.head(1)

,id,name,age,weight,height,gender,address,job,email,signup
0,1,이상현,63,161,18,여성,인천광역시 성북구 잠실길 지하430,중식 주방장 및 조리사,blakeerik@example.com,2025-08-13

In [14]:
column = ["id", "name", "age", "height", "weight", "gender", "address", "job", "email", "signup"]
source_dataframe = pd.DataFrame(data, columns=column)
source_dataframe.head(1)

,id,name,age,height,weight,gender,address,job,email,signup
0,1,이상현,63,18,161,여성,인천광역시 성북구 잠실길 지하430,중식 주방장 및 조리사,blakeerik@example.com,2025-08-13

### Pandas DataFrame 파일 쓰기

In [15]:
source_dataframe.to_csv("./data/customers.csv", index=False, header=False, sep="|")
source_dataframe.to_json("./data/customers.json", orient="records")
source_dataframe.to_pickle("./data/customers.pickle")
source_dataframe.to_parquet("./data/customers.parquet")

### Pandas DataFrame 파일 읽기

In [16]:
# dataframe = pd.read_csv("./data/customers.csv", header=None, sep="|", names=column)
# dataframe = pd.read_json("./data/customers.json")
# dataframe = pd.read_parquet("./data/customers.parquet")
dataframe = pd.read_pickle("../data/customers.pickle")

In [23]:
pd.set_option("display.max_colwidth", None)
dataframe[["address", "email"]].head()
dataframe.head(1)

,id,name,age,height,weight,gender,address,job,email,signup,bmi
0,1,이상현,63,18,161,여성,인천광역시 성북구 잠실길 지하430,중식 주방장 및 조리사,blakeerik@example.com,2025-08-13,4969.14

### Pandas Apply 맛보기

In [22]:
def calc_bmi(row):
    height_m = row["height"] / 100
    return round(row["weight"] / (height_m ** 2), 2)


dataframe["bmi"] = dataframe.apply(calc_bmi, axis=1)
dataframe.head(1)

Index(['id', 'name', 'age', 'height', 'weight', 'gender', 'address', 'job',
       'email', 'signup', 'bmi'],
      dtype='object')

,id,name,age,height,weight,gender,address,job,email,signup,bmi
0,1,이상현,63,18,161,여성,인천광역시 성북구 잠실길 지하430,중식 주방장 및 조리사,blakeerik@example.com,2025-08-13,4969.14